events {
    worker_connections 1024;
}

http{
    server {
        listen 80;
        listen 443;

        error_log /var/log/nginx/example-error.log;

        location / {
            proxy_pass http://localhost:8000;
        }
    }
}