services:
  app:
    image: test-project-app
    volumes:
      - ./app:/app
    command: python api.py
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

  web-proxy:
    image: nginx:alpine
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine # Образ с панелью управления
    container_name: rabbitmq
    ports:
      - "15672:15672"   # Порт ui-менеджмент
      - "5672:5672" # Порт для приложений (AMQP)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}    # Логин
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS} # Пароль
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Сохранение данных при перезапуске
    restart: on-failure

  db:
    image: postgres:16-alpine
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - ./db_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  ml_worker:
    build: ./ml_worker/
    restart: unless-stopped
    env_file:
      - ./ml_worker/.env
    volumes:
      - ./ml_worker:/app
    depends_on:
      - rabbitmq
    deploy:
      replicas: ${WORKER_AMOUNT}
  ollama:
    image: ollama/ollama
    container_name: gemma-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=gemma3:1b


volumes:
  rabbitmq_data:
  ollama_data:
